/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlquimiaChalesRouteImport } from './routes/alquimia-chales'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ValeDoSolRouteImport } from './routes/vale-do-sol'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlquimiaChalesRoute = AlquimiaChalesRouteImport.update({
  id: '/alquimia-chales',
  path: '/alquimia-chales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ValeDoSolRoute = ValeDoSolRouteImport.update({
  id: '/vale-do-sol',
  path: '/vale-do-sol',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alquimia-chales': typeof AlquimiaChalesRoute
  '/auth': typeof AuthRoute
  '/vale-do-sol': typeof ValeDoSolRoute
  '/metricas': typeof AuthenticatedMetricasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alquimia-chales': typeof AlquimiaChalesRoute
  '/auth': typeof AuthRoute
  '/vale-do-sol': typeof ValeDoSolRoute
  '/metricas': typeof AuthenticatedMetricasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alquimia-chales': typeof AlquimiaChalesRoute
  '/auth': typeof AuthRoute
  '/vale-do-sol': typeof ValeDoSolRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alquimia-chales' | '/auth' | '/vale-do-sol' | '/metricas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alquimia-chales' | '/auth' | '/vale-do-sol' | '/metricas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alquimia-chales'
    | '/auth'
    | '/vale-do-sol'
    | '/_authenticated/metricas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlquimiaChalesRoute: typeof AlquimiaChalesRoute
  AuthRoute: typeof AuthRoute
  ValeDoSolRoute: typeof ValeDoSolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alquimia-chales': {
      id: '/alquimia-chales'
      path: '/alquimia-chales'
      fullPath: '/alquimia-chales'
      preLoaderRoute: typeof AlquimiaChalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vale-do-sol': {
      id: '/vale-do-sol'
      path: '/vale-do-sol'
      fullPath: '/vale-do-sol'
      preLoaderRoute: typeof ValeDoSolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlquimiaChalesRoute: AlquimiaChalesRoute,
  AuthRoute: AuthRoute,
  ValeDoSolRoute: ValeDoSolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
